### ISSUE TITLE
[feature/goal-service] 목표 종료 API 기능 구현

### ISSUE THREAD

**Issue by dldmsql** [PomeTeam/POME_Server#126]
## Description
사용자가 목표를 종료하는 프로세스에 사용되는 종료 API 기능 개발

## To-do
- [x] Goal 엔티티에 종료인지 아닌지를 나타내는 상태 속성 추가
- [x] 목표 종료하기 API 기능 개발
- [x] 목표 도달까지 사용된 금액을 나타내는 속성 추가
