### ISSUE TITLE
[hotfix/goal-service] 목표 종료 시, 목표 성공여부를 DB에 반영

### ISSUE THREAD

**Issue by dldmsql** [PomeTeam/POME_Server#184]
## Description
목표를 종료한 뒤에 [완료된 목표] 탭에서 목표의 성공 여부가 보여짐을 피그마에서 확인했습니다.
따라서 목표 종료 시, 아래의 데이터를 DB에 반영합니다.
1. 목표의 종료 여부 ( false -> true )
2. 목표 종료에 대한 한 줄 코멘트 ( null -> "~~" )
3. 목표 성공 여부 ( false -> 목표가 갖는 소비 기록의 사용 금액 <= 목표 금액 )

## To-do
- [x] 목표 엔티티에 성공 여부 속성 추가 ( 기본은 false )
- [x] 목표 종료 API 호출 시, 서비스 레이어에서 성공 여부 계산
- [x] 포스트맨을 통한 테스트
