### ISSUE TITLE
[test/record-service] 기록 서비스 테스트 코드 작성

### ISSUE THREAD

**Issue by kingchan223** [PomeTeam/POME_Server#208]
## Description
Service layer의 단위 테스트 코드 작성

## To-do
- [x] 기록 생성 (성공)
- [x] 기록 단건 조회 (성공)
- [x] 기록 수정하기 (성공)
- [x] 기록 수정하기 (실패 - 요청자가 해당 기록의 주인이 아닌 경우)
- [x] 기록 삭제하기 (성공)
- [x] 기록에 두번째 감정 남기기 (성공 - 일반적인 경우)
- [x] 기록에 두번째 감정 남기기 (성공 - 첫번째는 긍정감정 두번째는 부정감점임 이때 마시멜로 솔직 카운트 증가)
- [x] 친구의 기록에 감정 남기기 (성공 - 감정을 처음 남기는 경우 <-- 마시멜로 공감 카운트 증가됨)
- [x] 친구의 기록에 감정 남기기 (성공 - 이미 기존에 감정을 남겼던 경우는 기존의 감정을 수정시킨다 <-- 마시멜로 공감 카운트 증가X)
