### ISSUE TITLE
[feature/user-information-cache] 도커 레디스 설치하고  user 정보(토큰)저장하기

### ISSUE THREAD

**Issue by kingchan223** [PomeTeam/POME_Server#22]
## Description
사용자 정보를 캐싱하기.
Pome Service는 AWS에서 제공하는 ElastiCache를 사용.

## To-do
- [x] DEV서버에 docker로 redis run후 작동 확인하기
- [x] DEV 서버의 redis-cli로 redis 접근 확인하기
- [x] PROD 서버에서 DEV 서버의 redis 접근 확인하기
- [x] redis에 사용자 정보 set, get 확인하기
