### ISSUE TITLE
[infra/build_test] 빌드 테스트 자동화 파이프라인 구축

### ISSUE THREAD

**Issue by dldmsql** [PomeTeam/POME_Server#27]
## Description
- 도입 목적
젠킨스 -> EC2 서버로 jar 파일 배포용
깃헙 액션 -> develop 브랜치와 main 브랜치에서의 코드 안정성 확보를 위한 빌드 테스트용

위와 같이 목적에 따른 역할 분리를 위해 도입하였습니다.
## To-do
- [x] 깃헙 액션으로 빌드 테스트 자동화
- [x] 젠킨스 실행 명령어 변경 ( clean build -> bootJar )
- [x] 젠킨스 빌드 시, slack 으로 알림 보내도록 설정 추가

## ETC
application.yml 프로퍼티 파일을 환경에 맞게 local, dev, prod로 분리 운영/관리함에 따라 깃헙 액션에서 사용되는 프로퍼티 파일의 raw 데이터를 [settings] > [secrets] > [actions] 에 미리 업로드 해야 합니다.
전체 프로퍼티 파일 내용을 모두 copy + paste 해서 넣으면 됩니다. ( jasypt password만 추가할 수 있는지에 대해서는 방법을 고민 중에 있습니다. )

**Comment by dldmsql** [comment]
[깃헙 액션으로 빌드 테스트 자동화하기](https://earth-95.tistory.com/107) 내용 참고
